version: "3.8"

services:

  nginx-proxy:
    image: nginx
    volumes:
      - ./website:/var/www/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/log:/var/log/nginx
      - ./docker/certs:/etc/nginx/certs
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - ${PORT_NGINX}:80
      - ${PORT_NGINX_SSL}:443
    depends_on:
      - php
      - db

  php:
    build: ./docker/php/
    container_name: talkto_php
    environment:
      - VIRTUAL_HOST=talkto_php.local
    depends_on:
      - db
    volumes:
      - ./website:/var/www/html
      - ./docker/php/php.ini:/etc/php/7.4/fpm/php.ini
    env_file:
      - .env

  db:
    platform: linux/amd64
    image: mysql:5.6.51
    container_name: talkto_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_LOGIN}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - talkto-data:/var/lib/mysql
      - ${MYSQL_DUMP_PATH}:/home/db.sql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        UPLOAD_LIMIT: 300M
        MEMORY_LIMIT: 2048M
        MAX_EXECUTION_TIME: 9000
    restart: always
    ports:
        - 8083:80
    links:
        - db
          
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./docker/certbot/www/:/var/www/certbot/:rw
  #     - ./docker/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  talkto-data:

networks:
  default:
    driver: bridge