<?php

//Spiriteo CMS

$mysqli = new mysqli($dbb_head['host'], "spiriteo", "m3UFeJ9382rPQ9m8tQPqM4es", "spiriteo");



$list_email = array('patlu30@gmx.fr',
'freu10@laposte.net',
'fredlu10@gmx.fr',
'galou20@gmx.fr',
'viot.ben@laposte.net',
'val.past@laposte.net',
'tazlou@gmx.fr',
'pascaltou@gmx.fr',
'mikeje@gmx.fr',
'michelote@gmx.fr',
'medbris@gmx.fr',
'maxjohn@gmx.fr',
'lou.pati@laposte.net',
'lou.bets@laposte.net',
'joupat@gmx.fr',
'josam@gmx.fr',
'johnmac@gmx.fr',
'jofreys@gmx.fr',
'joeygim@gmx.fr',
'joebrun@gmx.fr',
'jimfix@gmx.fr',
'jimcarte@gmx.fr',
'jeandul@gmx.fr',
'greglot@gmx.fr',
'ginalou@gmx.fr',
'gibob@gmx.fr',
'catjox@gmx.fr',
'carljohns@laposte.net',
'carljane@gmx.fr',
'carl.go@laposte.net',
'brucehari@gmx.fr',
'bout.lo@laposte.net',
'benoix@gmx.fr',
'benlou@gmx.fr',
'batloux@gmx.fr',
'batlou@gmx.fr',
'polfaut@gmx.fr',
'mariojot@gmx.fr',
'jofre@gmx.fr',
'joefree@gmx.fr',
'gigifo@gmx.fr',
'camp.louis@laposte.net',
'camillepois@gmx.fr',
'boutix@gmx.fr',
'betimoure@gmx.fr',
'benyou@gmx.fr',
'fatjack@gmx.fr',
'jenlou@gmx.fr',
'josin@gmx.fr',
'jolou10@laposte.net',
'jocoo@laposte.net',
'joboux@gmx.fr',
'lekiu10@laposte.net',
'leapo10@laposte.net',
'patlu130@laposte.net',
'patlu110@gmx.fr',
'loubou30@gmx.fr',
'loubo50@gmx.fr',
'loubo40@gmx.fr',
'lopoix100@laposte.net',
'lobo20@laposte.net',
'lobo10@laposte.net',
'patlu110@laposte.net',
'patju@gmx.fr',
'maxroyt@gmx.fr',
'loupok@gmx.fr',
'loubouy@gmx.fr',
'loubo70@gmx.fr',
'loubeg20@gmx.fr',
'loubeg10@gmx.fr',
'loubeg@gmx.fr',
'jomaxo@gmx.fr',
'jeanroye@gmx.fr',
'gofre@gmx.fr',
'fredloux@gmx.fr',
'fredjoa@gmx.fr',
'duluca@gmx.fr',
'camillepat@gmx.fr',
'patlu90@gmx.fr',
'luvu@gmx.fr',
'lulu1005@laposte.net',
'lulu1003@laposte.net',
'lobo60@gmx.fr',
'lomorre20@laposte.net',
'patlu40@laposte.net',
'patlu95@laposte.net',
'patlu95@gmx.fr',
'patlu90@laposte.net',
'patlu85@gmx.fr',
'patlu80@gmx.fr',
'patlu60@laposte.net',
'patlu55@laposte.net',
'patlu300@gmx.fr',
'patlu200@gmx.fr',
'patlu20@laposte.net',
'patlu140@laposte.net',
'patlu130@gmx.fr',
'patlu100@laposte.net',
'patlu100@gmx.fr',
'patlu70@gmx.fr',
'patlu400@gmx.fr',
'patlu70@laposte.net'
);


foreach($list_email as $email){
	var_dump("update users set active = '0' WHERE email = '{$email}'");
	$mysqli->query("update users set active = '0' WHERE email = '{$email}'");
	
}
exit;
?>